spring:
  h2:
    console:
      enabled: true
  datasource:
    username: beer_inventory_service
    password: 123
    url: jdbc:h2:mem:beer_inventory_service;DATABASE_TO_LOWER=TRUE;MODE=MYSQL
    drive-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true